// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0EvmTfeKwFSkoLgeTtEYXfxGYl9bs4w',
    appId: '1:446786939828:web:aebf3a61a036b63d68e0e1',
    messagingSenderId: '446786939828',
    projectId: 'stipres-flutter',
    authDomain: 'stipres-flutter.firebaseapp.com',
    storageBucket: 'stipres-flutter.firebasestorage.app',
    measurementId: 'G-3GZM17K4EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdNoIapU9tJWiWhhiatCLHv0WXHiCDgM',
    appId: '1:446786939828:android:cacd5d808a3f011f68e0e1',
    messagingSenderId: '446786939828',
    projectId: 'stipres-flutter',
    storageBucket: 'stipres-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDy8KvlEwvCYEKT35ZoLtpzxE0G6a6MQ',
    appId: '1:446786939828:ios:0cba6bde91da6b4568e0e1',
    messagingSenderId: '446786939828',
    projectId: 'stipres-flutter',
    storageBucket: 'stipres-flutter.firebasestorage.app',
    iosBundleId: 'com.example.stipres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwDy8KvlEwvCYEKT35ZoLtpzxE0G6a6MQ',
    appId: '1:446786939828:ios:0cba6bde91da6b4568e0e1',
    messagingSenderId: '446786939828',
    projectId: 'stipres-flutter',
    storageBucket: 'stipres-flutter.firebasestorage.app',
    iosBundleId: 'com.example.stipres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS0EvmTfeKwFSkoLgeTtEYXfxGYl9bs4w',
    appId: '1:446786939828:web:91754ca69e4194cf68e0e1',
    messagingSenderId: '446786939828',
    projectId: 'stipres-flutter',
    authDomain: 'stipres-flutter.firebaseapp.com',
    storageBucket: 'stipres-flutter.firebasestorage.app',
    measurementId: 'G-XH7HSC03DF',
  );
}
